ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import LoginPage,RegisterPage,HomePage
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', HomePage, name='home'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/$', LoginPage, name='login'),
    url(r'^register/$', RegisterPage, name='register'),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^products/', include("products.urls", namespace='products')),


]

if settings.DEBUG:
    urlpatterns=urlpatterns+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from .views import ProductListView, ProductDetailView, ProductFeaturedView

app_name='products'

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='home'),
    url(r'^featured/$', ProductFeaturedView.as_view(), name='featured'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),

]

search/urls.py
from django.conf.urls import url
from .views import SearchProductView
app_name='search'

urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name='query'),

]

products/models.py
from django.db import models
import os
import random
from datetime import datetime
from .utils import unique_slug_generator
from django.db.models.signals import pre_save
from django.urls import reverse

# Create your models here.


def upload_image_path(instance, filename):
    now = datetime.now()  #
    randint=random.randint(1,99999999)
    name, ext = os.path.splitext(os.path.basename(filename))
    return "products/{year}/{month}/{day}/{randint}{ext}".format(randint=randint, ext=ext, year=now.strftime("%Y"), month=now.strftime("%m"),\
                                                                 day=now.strftime("%d"))


class ProductManager(models.Manager):
    def get_by_id(self,id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs
        return None

    def get_by_slug(self,slug):
        qs = self.get_queryset().filter(slug=slug)
        if qs.count() == 1:
            return qs
        return None

    def featured(self):
        qs = self.get_queryset().filter(featured=True)
        if qs.count() == 1:
            return qs
        return None

class Product(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True,unique=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2,max_digits=10, default=0.00)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})

def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)

search/models.py
from django.db import models

# Create your models here.

ecommerce/forms.py
from django import forms
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

User=get_user_model()
class RegisterForm(forms.Form):
    username=forms.CharField()
    email=forms.EmailField()
    password=forms.CharField(widget=forms.PasswordInput)
    password2=forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    def clean_username(self):
        username=self.cleaned_data.get('username')
        qs=User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("Username already exists.")
        return username

    def clean_email(self):
        email=self.cleaned_data.get('email')
        qs=User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email already exists.")
        return email

    def clean(self):
        data=self.cleaned_data
        password=self.cleaned_data.get('password')
        password2=self.cleaned_data.get('password2')
        if password2 != password:
            raise forms.ValidationError('Passwords must match.')
        return data

ecommerce/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .forms import LoginForm,RegisterForm
from django.contrib.auth import authenticate,login,get_user_model


def HomePage(request):
    return render(request,"home.html",{})

def LoginPage(request):

    form=LoginForm(request.POST or None)
    print("not auth")
    context={}
    if form.is_valid():
        username=form.cleaned_data["username"]
        password=form.cleaned_data["password"]
        user=authenticate(request,username=username,password=password)
        print(user)
        if user is not None:
            login(request,user)
            #context['form']=LoginForm()
            print('auth')
            return redirect("/admin")
        else:
            context['error'] =  'Username or password incorrect'
    context={
            "form":form,
            }
    return render(request,"auth/login.html",context)

User=get_user_model()
def RegisterPage(request):
    form=RegisterForm(request.POST or None)
    if form.is_valid():
        print(form.cleaned_data)
        username=form.cleaned_data["username"]
        password=form.cleaned_data["password"]
        email=form.cleaned_data["email"]
        User.objects.create_user(username,email,password)
    context={
            "form":form,
            }
    return render(request,"auth/register.html",context)

products/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from django.http import Http404


from .models import Product
# Create your views here.


class ProductListView(ListView):
    queryset = Product.objects.all()


class ProductDetailView(DetailView):
    template_name = 'products/product_detail.html'
    queryset = Product.objects.all()

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        instance = Product.objects.get(slug=slug)
        return instance

class ProductFeaturedView(ListView):
    template_name = 'products/products-featured.html'

    def get_queryset(self):
        return Product.objects.filter(featured=True)

search/views.py
from django.shortcuts import render
from products.models import Product
from django.views.generic import ListView
from django.db.models import Q

# Create your views here.
class SearchProductView(ListView):
    template_name = 'search/search_list.html'
    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            lookups = Q(title__icontains=query) | Q(description__icontains=query)
            return Product.objects.filter(lookups).distinct()
        else:
            return Product.objects.none()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
{% include 'base/css.html' %}
{% block main_css %}{% endblock %}
</head>
<body>

{% include 'base/navbar.html' %}
<div class="container">
{% block content %}
{% endblock %}
{% include 'base/js.html' %}
</div>
</body>
</html>

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--<link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">-->
<link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

templates/base/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:featured' as featured %}
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'products:home' as products %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
<div class="container">
  <a class="navbar-brand" href="#">Drop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {%  if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {%  if request.path == products %}active{% endif %}">
        <a class="nav-link" href="{% url 'products:home' %}">Products</a>
      </li>
        <li class="nav-item {%  if request.path == featured %}active{% endif %}">
        <a class="nav-link" href="{% url 'products:featured' %}">Featured Products</a>
      </li>
    {% if request.user.is_authenticated %}
     <li class="nav-item {%  if request.path == login %}active{% endif %} ml-auto">
        <a class="nav-link" href="{% url 'login' %}">Logout</a>
      </li>
    {% else %}
         <li class="nav-item {%  if request.path == login %}active{% endif %}">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
         <li class="nav-item {%  if request.path == register %}active{% endif %}">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
    {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    {% include "search/snippets/search-form.html" %}
  </div>
</div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home Page{% endblock %}

{%  block content %}
    <h1>First Django E-Commerce Website</h1>
    <p>Hello World!</p>
{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% block title %}{{ object.title }}{% endblock %}
{%  block content %}
<p>{{ object.title | title}} <small>added {{ object.timestamp | timesince }} ago</small></p>
    <img class="img-fluid" src="{{ object.image.url }}" alt="Product Image">
<p>{{ object.description | linebreaks}}</p>
<p>{{ object.price }}</p>

{% endblock %}

templates/products/product_list.html
{% extends 'base.html' %}
{% block title %}Products List{% endblock %}
{%  block content %}
    <div class="row">
        {% if object_list %}
            {%  for obj in object_list %}
        <div class="col">
                {% include 'products/snippets/card.html' with instance=obj %}
        </div>
            {% endfor %}
        {% else %}
            <p>No products added yet.</p>
        {% endif %}

    </div>
    </div>
{% endblock %}

templates/products/products-featured.html
{% extends 'base.html' %}
{% block title %}Featured Items{% endblock %}
{%  block content %}
    {% if object_list %}
    {%  for obj in object_list %}
    <h1>{{  obj.title }}</h1>
    <p>{{ obj.description | truncatewords:50}}</p>
    <p>{{ obj.price }}</p>
    {% endfor %}
    {% else %}
    <p>No products added yet in the featured list</p>
    {% endif %}
{% endblock %}

templates/products/snippets/card.html
<div class="card" style="width: 18rem;">
    {% if instance.image %}
  <img src="{{ instance.image.url }}" class="card-img-top" alt="{{ instance.title }}">
    {% endif %}
  <div class="card-body">
      <h5 class="card-title">{{  instance.title }}{% if instance.featured %} <small>(this object is featured!)</small>{% endif %}</h5>
    <p class="card-text">{{ instance.description | truncatewords:50 }}</p>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">More Info</a>
  </div>
</div>

templates/products/snippets/snippets.html
<div class="card" style="width: 18rem;">
    {% if instance.image %}
  <img src="{{ instance.image.url }}" class="card-img-top" alt="{{ instance.title }}">
    {% endif %}
  <div class="card-body">
      <h5 class="card-title">{{  instance.title }}{% if instance.featured %} <small>(this object is featured!)</small>{% endif %}</h5>
    <p class="card-text">{{ instance.description }}</p>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">More Info</a>
  </div>
</div>

templates/search/search_list.html
{% extends 'base.html' %}
{% block title %}Search Results for '{{ request.GET.q }}'{% endblock %}
{%  block content %}
    <div class="row">
    {%  if request.GET.q %}
    <div class="col-12 mb-3 mt-3">
        Searched for "<b>{{ request.GET.q }}</b>≤"
        <hr>
    </div>
    {% else %}
    <div class="col-12 col-md-6 mx-auto py-5 ">
        {% include "search/snippets/search-form.html" %}

    </div>
    <div class="col-12"><hr></div>
        </div>

        <div class="row">
    {% endif %}
        {% if object_list %}
            {%  for obj in object_list %}
        <div class="col">
                {% include 'products/snippets/card.html' with instance=obj %}
        </div>
            {% endfor %}

        {% endif %}

    </div>
    </div>
{% endblock %}

templates/search/snippets/search-form.html
<form method="GET" action="{% url 'search:query' %}" class="form my-2 my-lg-0">
    <div class="input-group">
      <input class="form-control " type="search" placeholder="Search" name= 'q' aria-label="Search" value="{{ request.GET.q }}">
    <span class="input-group-btn">
      <button class="btn btn-outline-success" type="submit">Search</button>
            </span>
</div>
    </form>